# Site settings
title: Algoritics Internship Blog
header-img: img/img2-2.jpg
email: dfranco808@gmail.com
description: "Website being built for my summer internship"
baseurl: ""
url: "http://Dmize1.github.io"
twitter_username:
github_username:  Dmize1
facebook_username: 

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
